console.log("this is from the child_exception.js. It should crash since it will throw exception");

throw new Error("hello");

